[package]
name = "gitpush"
version = "0.1.9"
edition = "2021"
authors = ["Waldir Borba Junior <wborbajr@gmail.com>"]
description = "GitPush in rust!"
repository = "https://github.com/waldirborbajr/gitpush"
homepage = "https://github.com/waldirborbajr/gitpush"
readme  = "README.md"
keywords = ["gitpush", "devops", "git"]
license = "MIT"

[[bin]]
name = "gitpush"
path = "src/main.rs"

[dependencies]
names = "0.14.0"

[build]
rustflags = ["-z", "threads=8"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
opt-level = 'z' # Optimize for size
