[package]
name = "gitpush"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
names = "0.14.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
