edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
# imports_granularity = "One"
imports_granularity = "Module"
match_arm_leading_pipes = "Preserve"
normalize_doc_attributes = true
reorder_impl_items = true
tab_spaces = 2
unstable_features = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
